#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -q workq
#PBS -r n
#PBS -l walltime=48:00:00
#PBS -N SigmaRV_<<band_str>>_<<R>>_<<Teff>>_<<logg>>
# EVERYTHING ABOVE THIS COMMENT IS NECESSARY, SHOULD ONLY CHANGE nodes,ppn,walltime and my_job_name VALUES
cd $PBS_O_WORKDIR/SigmaRV
python sigmaRV_grid.py <<band_str>> <<R>> <<Teff>> <<logg>>
